buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:1.2-1.0.+'
    }
}

apply plugin: 'forge'

version = "1.7.10-v7"
group = "lain.mods.cos"
archivesBaseName = "CosmeticArmorReworked"

sourceCompatibility = '1.7'
targetCompatibility = '1.7'

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "run"
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}